/**
 * Khair Khwa Pharma — World Medicine (Turkey) product catalog
 */

const WM = {
  en: "Imported via World Medicine (Turkey). Contact us for availability, registration status, and batch documentation.",
  fa: "واردات از World Medicine (ترکیه). برای موجودی، وضعیت ثبت و اسناد بچ تماس بگیرید.",
  ps: "د ورلډ مېډیسن (ترکیه) له لارې واردات. د شتون، ثبت او بیچ اسنادو لپاره اړیکه ونیسئ.",
};

/**
 * box.layout — "tall" (syrup/suspension/injection) or "wide" (tablets/capsules)
 * box.primary / accent — brand colors from the World Medicine catalog
 */

export const products = [
  {
    id: "bravex",
    category: "pain",
    icon: "🧡",
    box: { layout: "tall", primary: "#f5821f", accent: "#d96612", brandColor: "#ffffff" },
    generic: { en: "Ibuprofen", fa: "ایبوپروفن", ps: "ایبوپروفین" },
    name: { en: "BRAVEX", fa: "براوکس", ps: "براوکس" },
    form: { en: "Oral suspension · 100 ml", fa: "شربت خوراکی · ۱۰۰ میلی‌لیتر", ps: "خوراکي شربت · ۱۰۰ میلی‌لیتر" },
    desc: {
      en: "Ibuprofen oral suspension — NSAID for fever and mild to moderate pain in children.",
      fa: "شربت ایبوپروفن — NSAID برای تب و درد خفیف تا متوسط در اطفال.",
      ps: "د ایبوپروفین شربت — د ماشومانو لپاره د تبې او سپک څخه منځني درد لپاره NSAID.",
    },
    details: {
      en: "Nonsteroidal anti-inflammatory (propionic acid derivative). Indicated for fever reduction, cold/flu symptoms, and mild pain (sore throat, teething, headache). Rx for juvenile rheumatoid arthritis.",
      fa: "ضد التهاب غیراستروئیدی. برای کاهش تب، علائم سرماخوردگی و درد خفیف. با نسخه برای آرتریت روماتوئیدیولن.",
      ps: "غیر سټیرویډي ضد التهاب. د تبې کمولو، زکام او سپک درد لپاره. د ماشومانو روماتوئید آرتریټ لپاره نسخه سره.",
    },
    wm: WM,
  },
  {
    id: "bronolac",
    category: "respiratory",
    icon: "🫁",
    box: { layout: "tall", primary: "#ff6f91", accent: "#9b4dca", brandColor: "#5b2c83" },
    generic: { en: "Ambroxol", fa: "آمبرکسول", ps: "امبروکسول" },
    name: { en: "BRONOLAC", fa: "برونولاک", ps: "برونولاک" },
    form: { en: "30 mg/5 ml syrup · 200 ml", fa: "شربت ۳۰ میلی‌گرام/۵ میلی‌لیتر · ۲۰۰ میلی‌لیتر", ps: "شربت ۳۰ میلی‌ګرام/۵ میلی‌لیتر · ۲۰۰ میلی‌لیتر" },
    desc: {
      en: "Ambroxol mucolytic syrup — secretolytic therapy for productive cough.",
      fa: "شربت آمبرکسول موکولیتیک — درمان سرفه خلط‌دار.",
      ps: "د امبروکسول موکولیتیک شربت — د خلط لرونکي ټخې درملنه.",
    },
    details: {
      en: "Mucolytic agent that increases secretion clearance in the respiratory tract. Used for acute and chronic bronchopulmonary diseases with abnormal mucus secretion.",
      fa: "مواد موکولیتیک برای پاکسازی ترشحات ریوی. در بیماری‌های برونشوپولمونری حاد و مزمن.",
      ps: "د تنفسي لارو د ترشحاتو پاکولو لپاره موکولیتیک. په حاد او مزمن برونشوپولمونري ناروغیو کې.",
    },
    wm: WM,
  },
  {
    id: "cefidant",
    category: "antibiotics",
    icon: "💊",
    box: { layout: "wide", primary: "#e91e63", accent: "#ad1457", brandColor: "#e91e63" },
    generic: { en: "Cefixime", fa: "سیفیکسیم", ps: "سیفیکسایم" },
    name: { en: "CEFIDANT", fa: "سیفیدانت", ps: "سیفیدانت" },
    form: { en: "400 mg · 10 film-coated tablets", fa: "۴۰۰ میلی‌گرام · ۱۰ قرص فیلم‌پوش", ps: "۴۰۰ میلی‌ګرام · ۱۰ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Cefixime — third-generation oral cephalosporin antibiotic.",
      fa: "سیفیکسیم — آنتی‌بیوتیک سفالوسپورین نسل سوم خوراکی.",
      ps: "سیفیکسایم — د دریم نسل خوراکي سیفالوسپورین انټي بایوټیک.",
    },
    details: {
      en: "Broad-spectrum bactericidal activity against gram-positive and gram-negative organisms. Indicated for upper/lower respiratory tract infections, urinary tract infections.",
      fa: "فعالیت باکتری‌کشی طیف‌گسترده. عفونت‌های تنفسی فوقانی/تحتانی و مجاری ادراری.",
      ps: "پراخه طیف باکتری وژونکی فعالیت. د تنفسي او ادراري لارو انفکشنونه.",
    },
    wm: WM,
  },
  {
    id: "coledan",
    category: "vitamins",
    icon: "☀️",
    box: { layout: "wide", primary: "#f5821f", accent: "#d96612", brandColor: "#ffffff" },
    generic: { en: "Vitamin D3 (Cholecalciferol)", fa: "ویتامین D3", ps: "ویټامین D3" },
    name: { en: "COLEDAN-D3", fa: "کولدان-D3", ps: "کولدان-D3" },
    form: { en: "20,000 IU · 14 soft capsules", fa: "۲۰٬۰۰۰ IU · ۱۴ کپسول نرم", ps: "۲۰٬۰۰۰ IU · ۱۴ نرم کپسول" },
    desc: {
      en: "Vitamin D3 soft capsules — prevention and treatment of vitamin D deficiency.",
      fa: "کپسول نرم ویتامین D3 — پیشگیری و درمان کمبود ویتامین D.",
      ps: "د ویټامین D3 نرم کپسول — د ویټامین D کمښت مخنیوی او درملنه.",
    },
    details: {
      en: "Cholecalciferol stimulates calcium absorption and regulates calcium/phosphate in bones and kidneys. For adolescents, adults, and elderly. Adjunct to osteoporosis therapy.",
      fa: "کلسی‌فریول جذب کلسیم را تحریک می‌کند. برای نوجوانان، بزرگسالان و سالمندان. مکمل درمان پوکی استخوان.",
      ps: "کولیکالسیفیرول د کلسیم جذب تحریک کوي. د ځوانانو، لویانو او زوړانو لپاره. د هډوکي کمزورۍ درملنې ملاتړ.",
    },
    wm: WM,
  },
  {
    id: "eksdelan",
    category: "gastro",
    icon: "💜",
    box: { layout: "wide", primary: "#7b3f99", accent: "#4a235a", brandColor: "#ffffff" },
    generic: { en: "Dexlansoprazole", fa: "دکسلانسوپرازول", ps: "ډیکسلانسوپرازول" },
    name: { en: "EKSDELAN", fa: "اکسدلان", ps: "اکسډلان" },
    form: { en: "30 mg · 28 delayed-release capsules", fa: "۳۰ میلی‌گرام · ۲۸ کپسول با تأخیر رهش", ps: "۳۰ میلی‌ګرام · ۲۸ وروسته خوشې کیدونکي کپسول" },
    desc: {
      en: "Dexlansoprazole — dual-delayed release PPI for GERD and erosive esophagitis.",
      fa: "دکسلانسوپرازول — مهارکننده پمپ پروتون با رهش دوگانه برای GERD.",
      ps: "ډیکسلانسوپرازول — د GERD لپاره دوه ډول خوشې کیدونکی پروټون پمپ انهیبitor.",
    },
    details: {
      en: "Proton pump inhibitor suppressing gastric acid via H+/K+-ATPase inhibition. Reversible, dose-dependent effect on basal and stimulated acid secretion.",
      fa: "مهارکننده پمپ پروتون با مهار H+/K+-ATPase. اثر معکوس و وابسته به دوز.",
      ps: "پروټون پمپ انهیبitor د H+/K+-ATPase بندولو سره. معکوس، دوز پورې اړوند اغیز.",
    },
    wm: WM,
  },
  {
    id: "fariktan",
    category: "pain",
    icon: "🔴",
    box: { layout: "tall", primary: "#e63946", accent: "#9d0208", brandColor: "#ffffff" },
    generic: { en: "Ibuprofen + Paracetamol", fa: "ایبوپروفن + پاراستامول", ps: "ایبوپروفین + پاراسیتامول" },
    name: { en: "FARIKTAN", fa: "فاریکتان", ps: "فاریکټان" },
    form: { en: "Oral suspension · 60 ml", fa: "شربت خوراکی · ۶۰ میلی‌لیتر", ps: "خوراکي شربت · ۶۰ میلی‌لیتر" },
    desc: {
      en: "Ibuprofen + Paracetamol combination — enhanced analgesic and antipyretic.",
      fa: "ترکیب ایبوپروفن + پاراستامول — مسکن و ضد تب قوی‌تر.",
      ps: "د ایبوپروفین + پاراسیتامول ترکیب — پیاوړی درد کمونکی او ضد تبه.",
    },
    details: {
      en: "Combination provides higher efficacy than individual components. For mild to moderate pain, headaches, migraines, toothaches, and fever from infectious/inflammatory diseases.",
      fa: "ترکیب اثربخشی بالاتری از اجزای جداگانه دارد. درد خفیف تا متوسط، سردرد، میگرن، دندان‌درد و تب.",
      ps: "ترکیب د جلا اجزاوو څخه لوړ اغیز لري. سپک څخه منځنی درد، سر درد، میګرین، غاښ درد او تبه.",
    },
    wm: WM,
  },
  {
    id: "flaprox",
    category: "antibiotics",
    icon: "🔵",
    box: { layout: "wide", primary: "#0066b3", accent: "#003f6b", brandColor: "#0066b3" },
    generic: { en: "Ciprofloxacin", fa: "سیپروفلوکساسین", ps: "سیپروفلوکساسین" },
    name: { en: "FLAPROX", fa: "فلاپروکس", ps: "فلاپروکس" },
    form: { en: "500 mg · 10 film-coated tablets", fa: "۵۰۰ میلی‌گرام · ۱۰ قرص فیلم‌پوش", ps: "۵۰۰ میلی‌ګرام · ۱۰ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Ciprofloxacin — broad-spectrum fluoroquinolone antibiotic.",
      fa: "سیپروفلوکساسین — آنتی‌بیوتیک فلوروکینولون طیف‌گسترده.",
      ps: "سیپروفلوکساسین — پراخه طیف فلوروکینولون انټي بایوټیک.",
    },
    details: {
      en: "Inhibits DNA-gyrase and topoisomerase IV. For respiratory, urinary, GI, skin/soft tissue, bone/joint infections, and anthrax prophylaxis.",
      fa: "مهار DNA-gyrase. عفونت‌های تنفسی، ادراری، گوارشی، پوستی و استخوان/مفصل.",
      ps: "DNA-gyrase بندوي. د تنفسي، ادراري، معدي، پوستکي او هډوکي/مفصل انفکشنونه.",
    },
    wm: WM,
  },
  {
    id: "lekoxa",
    category: "pain",
    icon: "💠",
    box: { layout: "wide", primary: "#56ccf2", accent: "#2f80ed", brandColor: "#ffffff" },
    generic: { en: "Celecoxib", fa: "سلکوکسیب", ps: "سیلیکوکسیب" },
    name: { en: "LEKOXA", fa: "لکوکسا", ps: "لکوکسا" },
    form: { en: "200 mg · 20 capsules", fa: "۲۰۰ میلی‌گرام · ۲۰ کپسول", ps: "۲۰۰ میلی‌ګرام · ۲۰ کپسول" },
    desc: {
      en: "Celecoxib — selective COX-2 inhibitor for inflammatory conditions.",
      fa: "سلکوکسیب — مهارکننده انتخابی COX-2 برای بیماری‌های التهابی.",
      ps: "سیلیکوکسیب — د COX-2 انتخابي انهیبitor د التهابي حالتونو لپاره.",
    },
    details: {
      en: "Selective COX-2 inhibitor with proven efficacy and safety. Symptomatic relief for osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis in adults.",
      fa: "مهارکننده انتخابی COX-2. تسکین علائم آرتروز، آرتریت روماتوئید و اسپوندیلیت آنکیلوزان.",
      ps: "د COX-2 انتخابي انهیبitor. د اوسټیوآرتریټ، روماتوئید آرتریټ او انکیلوزنګ سپونډیلایټس علامتونه کمول.",
    },
    wm: WM,
  },
  {
    id: "levoximed",
    category: "antibiotics",
    icon: "💉",
    box: { layout: "wide", primary: "#1e3a8a", accent: "#dc2626", brandColor: "#ffffff" },
    generic: { en: "Levofloxacin", fa: "لووفلوکساسین", ps: "لیوفلوکساسین" },
    name: { en: "LEVOXIMED", fa: "لووکسیمد", ps: "لیوکسیمېډ" },
    form: { en: "500 mg · 7 film-coated tablets", fa: "۵۰۰ میلی‌گرام · ۷ قرص فیلم‌پوش", ps: "۵۰۰ میلی‌ګرام · ۷ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Levofloxacin — fluoroquinolone for urinary and respiratory infections.",
      fa: "لووفلوکساسین — فلوروکینولون برای عفونت‌های ادراری و تنفسی.",
      ps: "لیوفلوکساسین — د ادراري او تنفسي انفکشنونو لپاره فلوروکینولون.",
    },
    details: {
      en: "Synthetic fluoroquinolone acting on DNA-gyrase. For acute pyelonephritis, complicated UTI, chronic bacterial prostatitis, and inhalation anthrax.",
      fa: "فلوروکینولون مصنوعی. پیلونفریت حاد، UTI پیچیده، پروستاتیت باکتریایی مزمن.",
      ps: "مصنوعي فلوروکینولون. حاد پاییلونفریټس، پیچل UTI، مزمن باکتریایی پروستاتیت.",
    },
    wm: WM,
  },
  {
    id: "loxodol",
    category: "pain",
    icon: "🩹",
    box: { layout: "wide", primary: "#c0392b", accent: "#2c3e50", brandColor: "#c0392b" },
    generic: { en: "Meloxicam", fa: "ملوکسیکام", ps: "میلوکسیکام" },
    name: { en: "LOXIDOL", fa: "لوکسیدول", ps: "لوکسیدول" },
    form: { en: "15 mg · 10 tablets", fa: "۱۵ میلی‌گرام · ۱۰ قرص", ps: "۱۵ میلی‌ګرام · ۱۰ حبوب" },
    desc: {
      en: "Meloxicam — oxicam NSAID for arthritis and spondylitis.",
      fa: "ملوکسیکام — NSAID اکسیکام برای آرتریت و اسپوندیلیت.",
      ps: "میلوکسیکام — د آرتریټ او سپونډیلایټس لپاره اکسیکام NSAID.",
    },
    details: {
      en: "Oxicam NSAID with anti-inflammatory, analgesic, and antipyretic properties. Short-term arthrosis therapy and long-term rheumatoid arthritis or ankylosing spondylitis.",
      fa: "NSAID اکسیکام با خواص ضد التهاب و مسکن. درمان کوتاه‌مدت آرتروز و درمان بلندمدت آرتریت روماتوئید.",
      ps: "د التهاب ضد او درد کمونکي اکسیکام NSAID. لنډمهاله اوسټیوآرتریټ او اوږدمهاله روماتوئید آرتریټ درملنه.",
    },
    wm: WM,
  },
  {
    id: "medolapram",
    category: "cns",
    icon: "🧠",
    box: { layout: "wide", primary: "#1bb295", accent: "#0e6b58", brandColor: "#5b2c83" },
    generic: { en: "Escitalopram", fa: "اسسیتالوپرام", ps: "ایسسیتالوپرام" },
    name: { en: "MEDOLAPRAM", fa: "مدولاپرام", ps: "مېډولاپرام" },
    form: { en: "10 mg · 28 film-coated tablets", fa: "۱۰ میلی‌گرام · ۲۸ قرص فیلم‌پوش", ps: "۱۰ میلی‌ګرام · ۲۸ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Escitalopram — SSRI antidepressant for depression and anxiety disorders.",
      fa: "اسسیتالوپرام — SSRI ضد افسردگی برای افسردگی و اختلالات اضطرابی.",
      ps: "ایسسیتالوپرام — د خپګانې او اضطرابي اختلالاتو لپاره SSRI ضد افسردګي.",
    },
    details: {
      en: "Selective serotonin reuptake inhibitor. Indicated for major depressive episodes, panic disorder, social anxiety, generalised anxiety, and obsessive-compulsive disorder.",
      fa: "مهارکننده بازجذب انتخابی سروتونین. افسردگی اساسی، اختلال پانیک، اضطراب اجتماعی و OCD.",
      ps: "د سروتونین انتخابي بیا جذب انهیبitor. لوی خپګانې، پانیک اختلال، ټولنیز اضطراب او OCD.",
    },
    wm: WM,
  },
  {
    id: "oncecef",
    category: "antibiotics",
    icon: "💉",
    box: { layout: "tall", primary: "#7b3f99", accent: "#4a235a", brandColor: "#7b3f99" },
    generic: { en: "Ceftriaxone", fa: "سفتریاکسون", ps: "سیفټریاکسون" },
    name: { en: "ONCECEF", fa: "وانسسف", ps: "ونسسیف" },
    form: { en: "1 g powder + solvent for injection", fa: "۱ گرم پودر + حلال برای تزریق", ps: "۱ ګرام پوډر + د انډول لپاره حل کوونکی" },
    desc: {
      en: "Ceftriaxone — third-generation cephalosporin for injection.",
      fa: "سفتریاکسون — سفالوسپورین نسل سوم برای تزریق.",
      ps: "سیفټریاکسون — د دریم نسل سیفالوسپورین د انډول لپاره.",
    },
    details: {
      en: "Broad-spectrum cephalosporin for bacterial meningitis, pneumonia, otitis media, intra-abdominal infections, UTI, bone/joint, skin/soft tissue, gonorrhea, syphilis, and endocarditis.",
      fa: "سفالوسپورین طیف‌گسترده. مننژیت، پنومونی، اوتیت، عفونت‌های شکمی، UTI، استخوان/مفصل.",
      ps: "پراخه طیف سیفالوسپورین. مننژایټس، نمونیا، اوتیت، د خېټې انفکشنونه، UTI، هډوکي/مفصل.",
    },
    wm: WM,
  },
  {
    id: "pompezo",
    category: "gastro",
    icon: "💚",
    box: { layout: "wide", primary: "#4caf50", accent: "#1b4332", brandColor: "#ffffff" },
    generic: { en: "Esomeprazole", fa: "اسومپرازول", ps: "ایسومپرازول" },
    name: { en: "POMPEZO", fa: "پومپزو", ps: "پومپزو" },
    form: { en: "40 mg · 14 delayed-release capsules", fa: "۴۰ میلی‌گرام · ۱۴ کپسول با تأخیر رهش", ps: "۴۰ میلی‌ګرام · ۱۴ وروسته خوشې کیدونکي کپسول" },
    desc: {
      en: "Esomeprazole — PPI for acid-related gastrointestinal disorders.",
      fa: "اسومپرازول — مهارکننده پمپ پروتون برای اختلالات اسیدی معده.",
      ps: "ایسومپرازول — د معدې اسیدي اختلالاتو لپاره پروټون پمپ انهیبitor.",
    },
    details: {
      en: "Proton pump inhibitor for conditions requiring gastric acid reduction. Typical dosing 20–40 mg daily.",
      fa: "مهارکننده پمپ پروتون برای کاهش اسید معده. دوز معمول ۲۰–۴۰ میلی‌گرام روزانه.",
      ps: "د معدې اسید کمولو لپاره پروټون پمپ انهیبitor. معمولي دوز ۲۰–۴۰ میلی‌ګرام ورځنی.",
    },
    wm: WM,
  },
  {
    id: "rofloxan",
    category: "antibiotics",
    icon: "🟣",
    box: { layout: "wide", primary: "#1a5fb4", accent: "#dc2626", brandColor: "#1a5fb4" },
    generic: { en: "Ofloxacin", fa: "افلوکساسین", ps: "افلوکساسین" },
    name: { en: "ROFLOXAN", fa: "روفلوکسان", ps: "روفلوکسان" },
    form: { en: "200 mg · 10 film-coated tablets", fa: "۲۰۰ میلی‌گرام · ۱۰ قرص فیلم‌پوش", ps: "۲۰۰ میلی‌ګرام · ۱۰ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Ofloxacin — fluoroquinolone for genitourinary and respiratory infections.",
      fa: "افلوکساسین — فلوروکینولون برای عفونت‌های ادراری-تناسلی و تنفسی.",
      ps: "افلوکساسین — د ادراري-تولیدي او تنفسي انفکشنونو لپاره فلوروکینولون.",
    },
    details: {
      en: "Fluoroquinolone active against gram-negative and gram-positive organisms. For genitourinary infections, pelvic inflammatory disease, respiratory infections, and COPD exacerbation.",
      fa: "فلوروکینولون فعال علیه ارگانیسم‌های گرم منفی و مثبت. عفونت‌های ادراری، التهاب لگن، عفونت‌های تنفسی.",
      ps: "د منفي او مثبت باکتریو ضد فلوروکینولون. ادراري انفکشنونه، د حوض التهاب، تنفسي انفکشنونه.",
    },
    wm: WM,
  },
  {
    id: "seramol",
    category: "gastro",
    icon: "🟢",
    box: { layout: "wide", primary: "#1bb295", accent: "#e91e63", brandColor: "#0d4a8f" },
    generic: { en: "Omeprazole", fa: "امپرازول", ps: "اومپرازول" },
    name: { en: "SERAMOL", fa: "سرامول", ps: "سرامول" },
    form: { en: "20 mg · 28 micropellet capsules", fa: "۲۰ میلی‌گرام · ۲۸ کپسول میکروپلت", ps: "۲۰ میلی‌ګرام · ۲۸ مایکروپلت کپسول" },
    desc: {
      en: "Omeprazole micropellet capsules — PPI for gastric acid control.",
      fa: "کپسول میکروپلت امپرازول — مهارکننده پمپ پروتون.",
      ps: "د اومپرازول مایکروپلت کپسول — د معدې اسید کنټرول پروټون پمپ انهیبitor.",
    },
    details: {
      en: "Specific inhibitor of the gastric acid pump in parietal cells. Rapid onset with once-daily dosing for acid-related disorders.",
      fa: "مهارکننده اختصاصی پمپ اسید معده. شروع سریع با دوز روزانه یکبار.",
      ps: "د معدې اسید پمپ ځانګړی انهیبitor. د ورځې یو ځل دوز سره ګړندی پیل.",
    },
    wm: WM,
  },
  {
    id: "syrpil",
    category: "pain",
    icon: "💧",
    box: { layout: "tall", primary: "#3b3b98", accent: "#e91e63", brandColor: "#ffffff" },
    generic: { en: "Paracetamol", fa: "پاراستامول", ps: "پاراسیتامول" },
    name: { en: "SYRPIL", fa: "سیرپیل", ps: "سیرپیل" },
    form: { en: "10 mg/ml · 100 ml I.V. infusion", fa: "۱۰ میلی‌گرام/میلی‌لیتر · ۱۰۰ میلی‌لیتر وریدی", ps: "۱۰ میلی‌ګرام/میلی‌لیتر · ۱۰۰ میلی‌لیتر وریدي انفیوژن" },
    desc: {
      en: "Paracetamol I.V. infusion — fast-acting analgesic and antipyretic.",
      fa: "انفوزیون وریدی پاراستامول — مسکن و ضد تب سریع‌الاثر.",
      ps: "د پاراسیتامول وریدي انفیوژن — ګړندی درد کمونکی او ضد تبه.",
    },
    details: {
      en: "Pain relief within 5–10 minutes of infusion start. Peak effect in 1 hour, duration 4–6 hours. For moderate pain (especially post-surgery) and fever when IV route is justified.",
      fa: "تسکین درد ظرف ۵–۱۰ دقیقه. اوج اثر در ۱ ساعت. برای درد متوسط (به‌ویژه پس از جراحی) و تب.",
      ps: "د انفیوژن پیل ۵–۱۰ دقیقو کې درد کمول. په ۱ ساعت کې لوړ اغیز. منځنی درد (ځانګړې عملیات وروسته) او تبه.",
    },
    wm: WM,
  },
  {
    id: "ziromin",
    category: "antibiotics",
    icon: "🧪",
    box: { layout: "wide", primary: "#dc2626", accent: "#7f1d1d", brandColor: "#ffffff" },
    generic: { en: "Azithromycin", fa: "آزیترومایسین", ps: "ازیترومایسین" },
    name: { en: "ZIROMIN", fa: "زیزومین", ps: "زیرومین" },
    form: { en: "500 mg · 3 film-coated tablets", fa: "۵۰۰ میلی‌گرام · ۳ قرص فیلم‌پوش", ps: "۵۰۰ میلی‌ګرام · ۳ فلم پوښ لرونکي حبوب" },
    desc: {
      en: "Azithromycin — macrolide antibiotic for respiratory and STI infections.",
      fa: "آزیترومایسین — آنتی‌بیوتیک ماکرولید برای عفونت‌های تنفسی.",
      ps: "ازیترومایسین — د تنفسي انفکشنونو لپاره ماکرولایډ انټي بایوټیک.",
    },
    details: {
      en: "Azalide macrolide inhibiting bacterial protein synthesis. For upper/lower respiratory infections, otitis media, skin/soft tissue infections, and uncomplicated STIs.",
      fa: "ماکرولید آزالید. عفونت‌های تنفسی فوقانی/تحتانی، اوتیت، عفونت‌های پوستی.",
      ps: "ازالایډ ماکرولایډ. د تنفسي پورتنۍ/تړ پورتنۍ انفکشنونه، اوتیت، پوستکي انفکشنونه.",
    },
    wm: WM,
  },
];
